AllCops:
  NewCops: disable
  TargetRubyVersion: '2.6'
  Exclude:
    - 'config.ru'
    - 'bin/*'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/deploy/*.rb'
    - 'config/environment.rb'
    - 'config/environments/*.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/puma.rb'
    - 'config/schedule.rb'
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# 需要逻辑整理
Lint/UselessAssignment:
  Exclude:
    - 'app/models/order.rb'

# 需要逻辑整理
Lint/SelfAssignment:
  Exclude:
    - 'app/models/agent.rb'

# Offense count: 65
# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 289

# Offense count: 16
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 480

# Offense count: 6
# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 4

# Offense count: 6
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 466
  Exclude:
    - 'app/controllers/orders_controller.rb'

Metrics/CyclomaticComplexity:
  Max: 45

Metrics/MethodLength:
  Max: 109

Metrics/ModuleLength:
  Max: 211

Metrics/PerceivedComplexity:
  Max: 51

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/NumericPredicate:
  Enabled: false

Style/SoleNestedConditional:
  Exclude:
    - 'app/helpers/incomes_helper.rb'

Layout/LineLength:
  Max: 195
