# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/**'
    - 'db/**/**'
    - 'lib/**/**'
    - 'app/models/order.rb'
    - 'config/initializers/qiniu_sdk.rb'
    - 'app/helpers/orders_helper.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/orders_controller.rb'
    - 'app/controllers/sents_controller.rb'
    - 'app/controllers/indents_controller.rb'
    - 'app/controllers/sent_lists_controller.rb'
    - 'app/controllers/incomes_controller.rb'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false