# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

secret_keys:

APP_NAME:

# 邮箱配置
EMAIL_ADDRESS:
EMAIL_PORT:
EMAIL_DOMAIN:
EMAIL_AUTH:
EMAIL_ESA:
EMAIL_USERNAME:
EMAIL_SENDER:
EMAIL_PASSWORD:

development:
  DATABASE_USERNAME: root
  DATABASE_PASSWORD:

test:
  DATABASE_USERNAME: root
  DATABASE_PASSWORD:

staging:
  DATABASE_USERNAME: root
  DATABASE_PASSWORD:

production:
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: