default: &default
  # adapter: mysql2
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: 'jjerp_dev'

test:
  <<: *default
  database: 'jjerp_test'

staging:
  <<: *default
  database: 'jjerp_staging'

production:
  <<: *default
  database: 'jjerp_pro'
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
